package ru.geekbrains.geekbrains_popular_libraries_kotlin.mvp.presenter.list

import ru.geekbrains.geekbrains_popular_libraries_kotlin.mvp.view.list.IHouseItemView

interface IHousesListPresenter: IListPresenter<IHouseItemView>